version: '3'
services:
  database:
    image: 'postgres:13'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: '${DATABASE_NAME}'
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DATABASE_NAME}", "-U", "${DATABASE_USERNAME}" ]
      retries: 3
      timeout: 5s

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

volumes:
  postgres:
    driver: local
