name: Automatic review

on:
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["backend", "frontend"]

    steps:
      - uses: actions/checkout@v3

      - run: corepack enable

      - run: pnpm install
        working-directory: "${{ matrix.package }}"

      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: 'src/'
          workdir: "${{ matrix.package }}"
