---
name: sast
on:
  pull_request:

jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: NodeJS Scan
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '.'
