---
name: sast
on:
  push:
  pull_request:

jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: NodeJS Scan
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '.'

  eslint:
    name: ESlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: eslint "{src,apps,libs,test}/**/*.ts"